---
# tasks file for docker

- name: Install required system packages
  ansible.builtin.package:
    name: {{ item }} 
    state: latest 
    update_cache: yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: install docker
  ansible.builtin.package:
    name: docker-ce
    state: latest