---
# tasks file for postgresql-server

- name: "Install packages"
  apt:  
    name: postgresql-{{ postgresql_version }}
    state: present


#--------------------------------------------
- name: Start and enable postgresql
  service: 
    name: postgresql
    state: started 
    enabled: yes